ydlidar_node:
  ros__parameters:
    port: /dev/lidar
    baudrate: 128000
    frame_id: laser_frame
    lidar_type: 1
    device_type: 0
    samp_rate: 5
    frequency: 10.0
    angle_min: -180.0
    angle_max: 180.0
    min_range: 0.1
    max_range: 12.0
    resolution_fixed: true
    singleChannel: false
    auto_reconnect: true
    isToFLidar: false
    ignore_array: ""
    intensity: false
    support_motor_dtr_ctrl: true
    abnormal_check_count: 4
